tag:
  otel:
    exporter:
      otlp:
        endpoint: http://localhost:4318
  spring:
    datasource:
      url: jdbc:postgresql://localhost:5433/azeroth_intel_db
      username: azeroth_data_writer_user
      password: 57f783GB8YLIgn3g0a0A
